"""
    TrainingConfig(; kwargs...)

All hyperparameters for `calibrate!`. Use `quick_test_config()` for fast smoke tests.
"""
Base.@kwdef struct TrainingConfig
    spinup_days         :: Int       = 180
    batch_days          :: Float64   = 3.0
    samples_per_batch   :: Int       = 20
    max_batches         :: Int       = 300
    loss_window_size    :: Int       = 20
    loss_threshold      :: Float32   = 500f0
    patience            :: Int       = 30
    grad_clip           :: Float32   = 5f0
    enable_lr_decay     :: Bool      = true
    lr_decay_factor     :: Float32   = 0.5f0
    lr_plateau_patience :: Int       = 50
    min_lr              :: Float32   = 1f-6
    max_lr_decays       :: Int       = 3
    trunc               :: Int       = 31
    nlayers             :: Int       = 8
    start_date          :: DateTime  = DateTime(2000, 3, 21)
    verbose             :: Bool      = true
    warmup_enzyme       :: Bool      = true
    daily_cycle         :: Bool      = true
end

"""Return a minimal config for quick smoke tests (trunc=5, 5 batches, 5-day spinup)."""
quick_test_config(; kw...) = TrainingConfig(;
    trunc       = 5,
    nlayers     = 3,
    spinup_days = 5,
    max_batches = 5,
    verbose     = true,
    kw...
)

# Result type

"""
    TrainingResult

Returned by `calibrate!`. Contains the full training history, final parameter
values, convergence information, and the config objects used.

Use `save(result, path)` / `load_result(path)` for resume-safe long runs.
"""
struct TrainingResult
    history      :: Dict{Symbol,Vector}
    final_params :: Dict{Symbol,Float32}
    conv_info    :: NamedTuple
    config       :: TrainingConfig
    loss_config  :: LossConfig
    param_specs  :: Vector{ParamSpec}
end

function Base.show(io::IO, r::TrainingResult)
    n = r.conv_info.total_batches
    @printf(io, "TrainingResult(%d batches, stop=%s, best_loss=%.4f)",
            n, r.conv_info.stop_reason, r.conv_info.best_smoothed_loss)
end

# Serialisation

"""Save a `TrainingResult` to a JLD2 file."""
function save_result(result::TrainingResult, path::AbstractString)
    jldopen(path, "w") do f
        f["result"] = result
    end
    return path
end

"""Load a `TrainingResult` from a JLD2 file."""
function load_result(path::AbstractString)
    jldopen(path, "r") do f
        return f["result"]
    end
end

"""
    save_artifacts(result, dir)

Write all training artifacts to `dir`:
- `result.jld2`: full `TrainingResult` (resumable via `load_result`)
- `training.log`: complete text log (same content as verbose output)
- `history.csv`: per-batch tabular data for plotting
- `final_weights.toml`: human-readable final parameter values and bounds
- `config.toml`: `TrainingConfig` used for this run
"""
function save_artifacts(result::TrainingResult, dir::AbstractString)
    mkpath(dir)

    save_result(result, joinpath(dir, "result.jld2"))
    _write_history_csv(result, joinpath(dir, "history.csv"))
    _write_final_weights_toml(result, joinpath(dir, "final_weights.toml"))
    _write_config_toml(result.config, joinpath(dir, "config.toml"))
    return dir
end

function _write_history_csv(result::TrainingResult, path::AbstractString)
    h = result.history
    isempty(h[:batch]) && return
    cols = collect(keys(h))
    sort!(cols)                        # deterministic column order
    # put the key columns first for readability
    priority = [:batch, :loss, :smoothed_loss, :lr, :elapsed_time, :param_change]
    ordered  = vcat(priority, filter(c -> c ∉ priority, cols))
    open(path, "w") do io
        println(io, join(string.(ordered), ","))
        n = length(h[:batch])
        for i in 1:n
            vals = [string(h[c][i]) for c in ordered]
            println(io, join(vals, ","))
        end
    end
end

function _write_final_weights_toml(result::TrainingResult, path::AbstractString)
    open(path, "w") do io
        println(io, "# Final trained parameter values")
        println(io, "# Generated by SpeedyCalibration.jl on $(Dates.now())\n")
        println(io, "[weights]")
        for spec in result.param_specs
            v = get(result.final_params, spec.name, NaN32)
            println(io, "$(spec.name) = $v")
        end
        println(io, "\n[bounds]  # [lower, upper] for each parameter")
        for spec in result.param_specs
            println(io, "$(spec.name) = [$(spec.bounds[1]), $(spec.bounds[2])]")
        end
        println(io, "\n[initial]  # values at start of training")
        for spec in result.param_specs
            init_str = isnothing(spec.initial) ? "\"default\"" : string(spec.initial)
            println(io, "$(spec.name) = $init_str")
        end
    end
end

function _write_config_toml(cfg::TrainingConfig, path::AbstractString)
    open(path, "w") do io
        println(io, "# TrainingConfig used for this run")
        println(io, "# Generated by SpeedyCalibration.jl on $(Dates.now())\n")
        for fname in fieldnames(TrainingConfig)
            v = getfield(cfg, fname)
            println(io, "$fname = $(repr(v))")
        end
    end
end

# TeeIO: write to two IOs simultaneously

struct _TeeIO <: IO
    a :: IO
    b :: IO
end
Base.write(t::_TeeIO, x::UInt8)                    = (write(t.a, x); write(t.b, x))
Base.write(t::_TeeIO, x::Vector{UInt8})            = (write(t.a, x); write(t.b, x); length(x))
Base.write(t::_TeeIO, x::AbstractVector{UInt8})    = (write(t.a, x); write(t.b, x); length(x))
Base.flush(t::_TeeIO)                              = (flush(t.a); flush(t.b))

# Returns the IO to use for all verbose/log output:
#   verbose + save_dir  → TeeIO(stdout, file)
#   verbose only        → stdout
#   save_dir only       → file
#   neither             → devnull
_output_io(verbose::Bool, log_io::Union{IO,Nothing}) =
    verbose && log_io !== nothing ? _TeeIO(stdout, log_io) :
    verbose                       ? stdout                  :
    log_io !== nothing            ? log_io                  : devnull

# Main entry point

"""
    calibrate!(param_specs, optimizer, loss_config, config; save_dir) → TrainingResult

Online statistical gradient calibration. Runs the model continuously and
averages single-timestep Enzyme gradients to estimate ∂L/∂θ robustly under
chaotic dynamics.

# Arguments
- `param_specs`: parameters to tune, each a `ParamSpec`
- `optimizer`: any Optimisers.jl optimizer, e.g. `Optimisers.Adam(5f-3)`
- `loss_config`: which fluxes to target, e.g. `TRENBERTH_LOSS`
- `config`: `TrainingConfig` with all hyperparameters
- `save_dir`: optional directory path; when set, writes `result.jld2`,
  `training.log`, `history.csv`, `final_weights.toml`, and `config.toml`

# Returns
A `TrainingResult` with full history, final parameter values, and convergence info.
"""
function calibrate!(
        param_specs  :: Vector{ParamSpec},
        optimizer,
        loss_config  :: LossConfig,
        config       :: TrainingConfig = TrainingConfig();
        save_dir     :: Union{AbstractString,Nothing} = nothing,
    )

    n_params    = length(param_specs)
    param_names = [spec.name for spec in param_specs]
    flux_keys   = loss_config.flux_keys

    # History initialisation
    history = Dict{Symbol,Vector}(
        :batch         => Int[],
        :loss          => Float32[],
        :smoothed_loss => Float32[],
        :elapsed_time  => Float64[],
        :param_change  => Float32[],
        :lr            => Float32[],
    )
    for k in flux_keys; history[k] = Float32[]; end
    for name in param_names
        history[name]                     = Float32[]
        history[Symbol("grad_",    name)] = Float32[]
        history[Symbol("gradstd_", name)] = Float32[]
    end
    loss_window = Float32[]

    # Build model
    sg     = SpectralGrid(trunc=config.trunc, nlayers=config.nlayers)
    planet = Earth(sg; daily_cycle=config.daily_cycle, seasonal_cycle=false)
    model  = PrimitiveWetModel(sg; planet=planet)
    p      = vec(parameters(model))

    init_phys = Float32[]
    for spec in param_specs
        val = isnothing(spec.initial) ?
              Float32(get_by_path(p, spec.path)) : spec.initial
        set_by_path!(p, spec.path, val)
        push!(init_phys, val)
    end
    model = SpeedyWeather.reconstruct(model, p)
    sim   = initialize!(model)
    sim.variables.prognostic.clock.time = config.start_date
    SpeedyWeather.initialize!(sim; period=Day(365*100), output=false)

    clock            = sim.variables.prognostic.clock
    steps_per_day    = ceil(Int, Millisecond(Day(1)).value / Millisecond(clock.Δt).value)
    batch_steps      = ceil(Int, config.batch_days * steps_per_day)
    steps_per_sample = max(1, batch_steps ÷ config.samples_per_batch)

    # Sigmoid reparameterisation
    opt_params  = Float32[to_raw(init_phys[i], spec.bounds[1], spec.bounds[2])
                          for (i, spec) in enumerate(param_specs)]
    phys_values = Float32[sigmoid_param(opt_params[i], spec.bounds[1], spec.bounds[2])
                          for (i, spec) in enumerate(param_specs)]

    opt_state  = Optimisers.setup(optimizer, opt_params)
    current_lr = optimizer isa Optimisers.Adam ? Float32(optimizer.eta) : NaN32

    best_smoothed_loss = Inf32
    batches_since_best = 0
    lr_decay_count     = 0
    prev_phys          = copy(phys_values)
    stop_reason        = "max batches reached"
    converged          = false
    start_time         = time()

    # Output IO setup
    log_file = save_dir !== nothing ? (mkpath(save_dir);
                                       open(joinpath(save_dir, "training.log"), "w")) : nothing
    io = _output_io(config.verbose, log_file)

    _print_header(io, param_specs, phys_values, opt_params, loss_config, config, current_lr)

    # Spinup
    @printf(io, "\nSpinup (%d days)...\n", config.spinup_days)
    t_spinup = time()
    for _ in 1:(config.spinup_days * steps_per_day)
        SpeedyWeather.timestep!(sim)
    end
    @printf(io, "Spinup complete in %.1f s.\n\n", time() - t_spinup)
    flush(io)

    # Enzyme warmup on the spun-up model
    # Must run AFTER spinup so that radiation/parameterization fields are
    # physically initialised. Running AD on a freshly-initialised model
    # (all-zero flux fields) produces NaN gradients that corrupt the state.
    if config.warmup_enzyme
        enzyme_warmup(sim, loss_config, param_specs)
    end

    println(io, "Starting training...")
    println(io, "-" ^ 70)

    # Batch loop
    for batch in 1:config.max_batches

        all_grads  = [Float32[] for _ in 1:n_params]
        flux_accum = Dict{Symbol,Vector{Float32}}(k => Float32[] for k in flux_keys)

        for _ in 1:config.samples_per_batch
            for _ in 1:steps_per_sample
                SpeedyWeather.timestep!(sim)
            end
            grads, means, _ = compute_gradients!(
                sim.variables, sim.model, loss_config, param_specs)

            if all(isfinite, grads) && all(isfinite(means[k]) for k in flux_keys)
                for (i, g) in enumerate(grads); push!(all_grads[i], g); end
                for k in flux_keys; push!(flux_accum[k], means[k]); end
            end
        end

        # advance any remainder of the batch window
        remainder = batch_steps - config.samples_per_batch * steps_per_sample
        for _ in 1:remainder; SpeedyWeather.timestep!(sim); end

        if isempty(flux_accum[flux_keys[1]])
            println(io, "Batch $batch: all gradient samples invalid, stopping.")
            stop_reason = "all gradient samples invalid"
            break
        end

        raw_mean_grads = Float32[mean(g) for g in all_grads]
        raw_std_grads  = Float32[length(g) > 1 ? std(g; corrected=false) : 0f0
                                 for g in all_grads]

        # apply per-param grad_scale and sigmoid chain-rule factor
        for i in 1:n_params
            raw_mean_grads[i] *= param_specs[i].grad_scale *
                sigmoid_grad_factor(opt_params[i],
                                    param_specs[i].bounds[1],
                                    param_specs[i].bounds[2])
        end

        mean_fluxes = Dict{Symbol,Float32}(k => mean(flux_accum[k]) for k in flux_keys)
        loss        = compute_loss(mean_fluxes, loss_config)
        elapsed     = time() - start_time

        # gradient clipping
        scaled_grads = copy(raw_mean_grads)
        grad_norm = sqrt(sum(scaled_grads .^ 2))
        if grad_norm > config.grad_clip
            scaled_grads .*= config.grad_clip / grad_norm
        end

        # smoothed loss + plateau detection
        push!(loss_window, loss)
        length(loss_window) > config.loss_window_size && popfirst!(loss_window)
        smoothed_loss = mean(loss_window)

        param_change = mean(abs.(phys_values .- prev_phys) ./
                            max.(abs.(phys_values), 1f-6))

        if smoothed_loss < best_smoothed_loss
            best_smoothed_loss = smoothed_loss
            batches_since_best = 0
        else
            batches_since_best += 1
        end

        # LR decay on plateau
        if config.enable_lr_decay &&
                batches_since_best >= config.lr_plateau_patience &&
                current_lr > config.min_lr &&
                lr_decay_count < config.max_lr_decays
            old_lr     = current_lr
            current_lr = max(current_lr * config.lr_decay_factor, config.min_lr)
            opt_state  = Optimisers.setup(Optimisers.Adam(current_lr), opt_params)
            batches_since_best = 0
            lr_decay_count += 1
            @printf(io, "  ↓ LR: %.2e → %.2e (decay #%d)\n",
                    old_lr, current_lr, lr_decay_count)
        end

        # optimizer step in unconstrained space
        prev_phys = copy(phys_values)
        opt_state, opt_params = Optimisers.update(opt_state, opt_params, scaled_grads)
        phys_values = Float32[sigmoid_param(opt_params[i], spec.bounds[1], spec.bounds[2])
                               for (i, spec) in enumerate(param_specs)]

        # reconstruct model with updated parameters
        _variables = sim.variables
        new_p = vec(parameters(sim.model))
        for (i, spec) in enumerate(param_specs)
            set_by_path!(new_p, spec.path, phys_values[i])
        end
        updated_model = SpeedyWeather.reconstruct(sim.model, new_p)
        updated_model.time_stepping.first_step_euler = false
        sim = Simulation(_variables, updated_model)

        # record history
        push!(history[:batch],         batch)
        push!(history[:loss],          loss)
        push!(history[:smoothed_loss], smoothed_loss)
        push!(history[:elapsed_time],  elapsed)
        push!(history[:param_change],  param_change)
        push!(history[:lr],            current_lr)
        for k in flux_keys
            push!(history[k], mean_fluxes[k])
        end
        for (i, name) in enumerate(param_names)
            push!(history[name],                     phys_values[i])
            push!(history[Symbol("grad_",    name)], raw_mean_grads[i])
            push!(history[Symbol("gradstd_", name)], raw_std_grads[i])
        end

        if batch <= 10 || batch % 5 == 0
            flux_str = join([@sprintf("%s=%5.1f", k, mean_fluxes[k])
                             for k in flux_keys], " ")
            @printf(io, "Batch %3d | LR %.1e | %s | L̄ %8.2f | Δp %.1e\n",
                    batch, current_lr, flux_str, smoothed_loss, param_change)
            flush(io)
        end

        if smoothed_loss < config.loss_threshold
            converged   = true
            stop_reason = "smoothed loss below threshold ($(config.loss_threshold))"
            @printf(io, "CONVERGED: smoothed_loss %.4f < %.4f\n",
                    smoothed_loss, config.loss_threshold)
            break
        end
    end

    final_params = Dict(spec.name => phys_values[i]
                        for (i, spec) in enumerate(param_specs))
    conv_info = (
        converged          = converged,
        stop_reason        = stop_reason,
        total_batches      = length(history[:batch]),
        best_smoothed_loss = best_smoothed_loss,
        total_time         = time() - start_time,
    )

    _print_summary(io, param_specs, init_phys, phys_values, history,
                   flux_keys, loss_config, conv_info)

    result = TrainingResult(history, final_params, conv_info, config, loss_config, param_specs)

    if save_dir !== nothing
        log_file !== nothing && close(log_file)
        save_artifacts(result, save_dir)
    end

    return result
end

# Logging helpers

function _print_header(io::IO, param_specs, phys_values, opt_params, loss_config, config, lr)
    println(io, "=" ^ 70)
    println(io, "SpeedyCalibration.jl: calibrate!")
    println(io, "=" ^ 70)
    for (i, spec) in enumerate(param_specs)
        gs = spec.grad_scale != 1f0 ? @sprintf("  [×%.0f]", spec.grad_scale) : ""
        @printf(io, "  %2d. %-32s = %.4f  [%.3f, %.3f]  raw₀=%.3f%s\n",
                i, spec.name, phys_values[i],
                spec.bounds[1], spec.bounds[2], opt_params[i], gs)
    end
    println(io, "-" ^ 70)
    for k in loss_config.flux_keys
        @printf(io, "  %4s  target=%6.1f W/m²  weight=%.2f\n",
                k, loss_config.targets[k], loss_config.weights[k])
    end
    println(io, "-" ^ 70)
    @printf(io, "LR: %.2e | grad_clip: %.2f | samples/batch: %d | loss_threshold: %.2f\n",
            lr, config.grad_clip, config.samples_per_batch, config.loss_threshold)
    println(io, "(sigmoid reparameterisation active)")
    println(io, "=" ^ 70)
end

function _print_summary(io::IO, param_specs, init_phys, phys_values,
                         history, flux_keys, loss_config, conv_info)
    println(io, "\n" * "=" ^ 70)
    println(io, "TRAINING SUMMARY")
    println(io, "=" ^ 70)
    for (i, spec) in enumerate(param_specs)
        @printf(io, "  %-32s %.4f → %.4f\n", spec.name, init_phys[i], phys_values[i])
    end
    println(io, "-" ^ 70)
    if isempty(history[:loss])
        println(io, "  (no batches completed)")
    else
        for k in flux_keys
            @printf(io, "  Final %-4s: %6.2f W/m²  (target: %.1f)\n",
                    k, history[k][end], loss_config.targets[k])
        end
        @printf(io, "Final smoothed loss: %.4f  |  best: %.4f\n",
                history[:smoothed_loss][end], conv_info.best_smoothed_loss)
    end
    @printf(io, "Stop: %s  |  time: %.1f s\n", conv_info.stop_reason, conv_info.total_time)
    println(io, "=" ^ 70)
end
